### ISSUE TITLE
ES5 setters are shown as 'getter' in console log

### ISSUE THREAD

**Issue by c69** [operasoftware/dragonfly#91] opened 2012-09-30 14:15 UTC
var a = {
 b: 1,
  get x () { return this.b; },
  set z (v) { return (this.b = v); }
}

When we inspect 'a' in console - we see: 

[-] Object 
b 1
x getter
z getter

**Comment by hzr** [comment] 2012-09-30 16:02
This is by design, click "getter" to evaluate.

**Comment by hzr** [comment] 2012-10-01 09:32
Sorry, read this too fast, this is clearly a problem. Reopening.

**Comment by hzr** [comment] 2012-10-01 10:12
No, closing again. I can't find it in the spec, but when you specify only a setter, a getter is automatically created with the value undefined. This is what you see.

**Closed as completed by hzr** 2012-10-01 10:12 UTC
Labels: invalid

**Comment by c69** [comment] 2012-10-01 22:47
ok, but How can i inspect a setter then ?

**Comment by rchl** [comment] 2012-10-01 23:51
Not sure what you mean by inspect a setter. I don't think you can obtain reference to the function that runs on setting value, if that's what you mean.

One might argue that 'getter' is a poor name for what not necessarily has to be a getter, in ecmascript sense. It could be a property that is just not 'trivial' to obtain and thus requires manual evaluation to get the value. Maybe we should rename 'getter' to 'fetch' or 'retrieve' for example.

**Comment by chriskr** [comment] 2012-10-02 07:22
You can do `a.__lookupSetter__("z")` which returns the setter or `Object.getOwnPropertyDescriptor(a, "z")` which returns an object with `configurable`, `enumerable`, `get` and `set`.

**Comment by c69** [comment] 2012-11-09 18:32
Thanx for the tip, this works.
